login:
  url: "https://owo.ecycloud.com/auth/login"

checkin:
  url: "https://owo.ecycloud.com/user/checkin"

user:
  - name: "first-user-name"
    email: "first-user-email"
    passwd: "first-user-passwd"
  - name: "second-user-name"
    email: "second-user-email"
    passwd: "second-user-passwd"
